name: hard_body_gym
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  provider: ^6.0.5
  firebase_core: ^2.30.1
  firebase_storage: ^11.7.4
  image_picker: ^1.1.1
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  ios: "Icon-App"
  android: true
  image_path: "assets/image/app/ic_launcher.png"
  adaptive_icon_background: "assets/image/app/ic_launcher_background.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/image/app/ic_launcher_foreground.png" # only available for Android 8.0 devices and above
  adaptive_icon_monochrome: "assets/image/app/ic_launcher_monochrome.png" # only available for Android 13 devices and above
  min_sdk_android: 21
  remove_alpha_ios: true
  background_color_ios: "#ffffff"

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/image/app/
